# Generated by Django 5.0.6 on 2024-05-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='First Name Here', max_length=100)),
                ('last_name', models.CharField(default='Last Name Here', max_length=100)),
                ('email', models.EmailField(default='Email Here', max_length=254, unique=True)),
                ('phone', models.CharField(default='Phone Number Here', max_length=15)),
                ('address', models.CharField(default='Address Here', max_length=100)),
                ('location', models.CharField(default='Location Here', max_length=100)),
                ('gender', models.CharField(default='Unknown', max_length=10)),
                ('age', models.IntegerField(default=0)),
                ('type_of_therapy', models.CharField(default='Cognitive Behavior', max_length=100)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('image', models.ImageField(default='therapists/default.jpg', upload_to='therapists/')),
                ('fee', models.IntegerField(default=0)),
                ('accepts_queer_clients', models.BooleanField(default=False)),
            ],
        ),
    ]
